name: test
on:
  push:
    branch: [ cicd ]
jobs:
  build:
    name: Build ${{ matrix.target }}
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        target: [ "apk --flavor dev -t lib/main_dev.dart --debug"]
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '12.x'
      - uses: subosito/flutter-action@v1
        with:
          flutter-version: '3.0.1'
      - run: flutter pub get
      - run: flutter test
      - run: flutter build ${{matrix.target}}
      - name: Push APK to Releases
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk"
          token: ${{ secrets.TOKEN2 }}
#        uses: ncipollo/release-action@v1
#        with:
#          artifacts: "build/app/outputs/flutter-apk/*.apk"
#          artifacts: "build/app/outputs/flutter-apk/*.apk"
#          token: ${{ secrets.TOKEN }}
